# Generated by Django 3.1.7 on 2021-03-10 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('rep', models.BooleanField(default=False)),
                ('superadmin', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=200, null=True)),
                ('speakerNum', models.IntegerField(default=0)),
                ('authClone', models.OneToOneField(db_column='authClone', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Delegate',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('shortName', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('votesWeight', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Institution',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, null=True)),
                ('yesVotes', models.IntegerField(default=0)),
                ('noVotes', models.IntegerField(default=0)),
                ('abstainVotes', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('anonymous', models.BooleanField(default=False)),
                ('repsOnly', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Poll',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote', models.IntegerField(default=0)),
                ('voteTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='councilApp.poll')),
                ('proxy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxy', to='councilApp.delegate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='councilApp.delegate')),
            ],
            options={
                'db_table': 'Vote',
            },
        ),
        migrations.AddField(
            model_name='delegate',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='councilApp.institution'),
        ),
    ]
