# Generated by Django 3.1.7 on 2021-03-07 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('rep', models.BooleanField(default=False)),
                ('superadmin', models.BooleanField(default=False)),
                ('institution', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('speakerNum', models.IntegerField(default=0)),
                ('authClone', models.OneToOneField(db_column='authClone', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Delegates',
            },
        ),
    ]
