# Generated by Django 3.1.7 on 2021-03-09 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, null=True)),
                ('yesVotes', models.IntegerField(default=0)),
                ('noVotes', models.IntegerField(default=0)),
                ('abstainVotes', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('anonymous', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Polls',
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote', models.IntegerField(default=0)),
                ('voteTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='councilApp.polls')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='councilApp.delegates')),
            ],
            options={
                'db_table': 'Votes',
            },
        ),
    ]
