# Generated by Django 3.1.7 on 2021-03-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0002_polls_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='rep',
            new_name='voter',
        ),
        migrations.AddField(
            model_name='polls',
            name='repsOnly',
            field=models.BooleanField(default=True),
        ),
    ]
