# Generated by Django 3.1.7 on 2021-03-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0003_vote_voteweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='outcome',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
