# Generated by Django 3.1.7 on 2021-03-14 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0005_auto_20210314_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='proxy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vote_proxy', to='councilApp.delegate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vote_voter', to='councilApp.delegate'),
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('activeTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiryTime', models.DateTimeField(null=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proxy_holder', to='councilApp.delegate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proxy_voter', to='councilApp.delegate')),
            ],
            options={
                'db_table': 'Proxy',
            },
        ),
    ]
