# Generated by Django 3.1.7 on 2021-03-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0006_auto_20210314_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='proxy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='councilApp.proxy'),
        ),
    ]
