# Generated by Django 3.1.7 on 2021-03-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0007_auto_20210314_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='votesWeight',
            field=models.IntegerField(default=1),
        ),
    ]
