# Generated by Django 3.1.7 on 2021-03-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0010_auto_20210318_1552'),
        ('councilApp', '0010_resettoken'),
    ]

    operations = [
    ]
