# Generated by Django 3.1.7 on 2021-03-19 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('councilApp', '0011_merge_20210319_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('regToken', models.BooleanField(null=True)),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Token',
            },
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['-point_of_order', 'index']},
        ),
        migrations.DeleteModel(
            name='ResetToken',
        ),
    ]
