# Generated by Django 3.1.7 on 2021-03-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0012_auto_20210319_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='regToken',
            new_name='isRegToken',
        ),
    ]
