# Generated by Django 3.1.7 on 2021-03-19 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('councilApp', '0013_auto_20210319_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('pronouns', models.CharField(max_length=100, null=True)),
                ('first_time', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='councilApp.institution')),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PendingRego',
            },
        ),
        migrations.CreateModel(
            name='ResetToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ResetToken',
            },
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
