# Generated by Django 3.1.7 on 2021-03-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0014_auto_20210319_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrego',
            name='user',
        ),
    ]
