# Generated by Django 3.1.7 on 2021-03-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0015_remove_pendingrego_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingrego',
            old_name='first_time',
            new_name='firstTime',
        ),
    ]
