# Generated by Django 3.1.7 on 2021-03-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0017_auto_20210320_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['index']},
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='point_of_order',
        ),
        migrations.AddField(
            model_name='speaker',
            name='intention',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
