# Generated by Django 3.1.7 on 2021-03-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0018_auto_20210324_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_node',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='councilApp.institution'),
        ),
    ]
