# Generated by Django 3.1.7 on 2021-03-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0019_auto_20210325_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='roll_call',
            field=models.BooleanField(default=False),
        ),
    ]
