# Generated by Django 5.2.15 on 2026-06-24 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0020_poll_roll_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discussion_type', models.CharField(choices=[('informal', 'Informal'), ('formal', 'Formal')], default='informal', max_length=20)),
                ('default_speaker_seconds', models.PositiveIntegerField(default=60)),
                ('active', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('timer_running', models.BooleanField(default=False)),
                ('timer_started_at', models.DateTimeField(blank=True, null=True)),
                ('timer_remaining_seconds', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_discussions', to='councilApp.delegate')),
            ],
            options={
                'db_table': 'Discussion',
                'ordering': ['-active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('current', 'Current'), ('done', 'Done'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_speaker_entries', to='councilApp.delegate')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='councilApp.discussion')),
            ],
            options={
                'db_table': 'DiscussionSpeaker',
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='discussion',
            name='current_speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_discussions', to='councilApp.discussionspeaker'),
        ),
        migrations.CreateModel(
            name='DiscussionParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_participations', to='councilApp.delegate')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='councilApp.discussion')),
            ],
            options={
                'db_table': 'DiscussionParticipant',
                'ordering': ['joined_at'],
                'unique_together': {('discussion', 'delegate')},
            },
        ),
    ]
