# Generated by Django 5.2.15 on 2026-06-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0021_discussion_discussionspeaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='account_role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('delegate', 'Delegate'), ('representative', 'Representative'), ('moderator', 'Moderator')], default='delegate', max_length=20),
        ),
        migrations.AddField(
            model_name='discussion',
            name='additional_moderators',
            field=models.ManyToManyField(blank=True, related_name='co_moderated_discussions', to='councilApp.delegate'),
        ),
        migrations.AddField(
            model_name='pendingrego',
            name='account_role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('delegate', 'Delegate'), ('representative', 'Representative'), ('moderator', 'Moderator')], default='delegate', max_length=20),
        ),
    ]
