# Generated by Django 5.2.15 on 2026-06-24 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0023_clear_discussions_and_non_admin_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_questions', to='councilApp.delegate')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='councilApp.discussion')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='councilApp.discussionquestion')),
            ],
            options={
                'db_table': 'DiscussionQuestion',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionQuestionReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('agree', 'Agree'), ('question', 'Question')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_question_reactions', to='councilApp.delegate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='councilApp.discussionquestion')),
            ],
            options={
                'db_table': 'DiscussionQuestionReaction',
                'unique_together': {('question', 'delegate', 'reaction')},
            },
        ),
    ]
