# Generated by Django 5.2.15 on 2026-06-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0025_clear_users_and_discussions_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionquestionreaction',
            name='reaction',
            field=models.CharField(choices=[('heart', 'Heart'), ('thumbs_up', 'Thumbs up'), ('thumbs_down', 'Thumbs down'), ('question', 'Question')], max_length=20),
        ),
        migrations.CreateModel(
            name='DiscussionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_events', to='councilApp.delegate')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='councilApp.discussion')),
            ],
            options={
                'db_table': 'DiscussionEvent',
                'ordering': ['-created_at'],
            },
        ),
    ]
