# Generated by Django 5.2.15 on 2026-06-24 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilApp', '0026_alter_discussionquestionreaction_reaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.CharField(blank=True, max_length=80)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'AgendaDay',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='delegate',
            name='account_role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('delegate', 'Delegate'), ('representative', 'Representative'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='delegate', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingrego',
            name='account_role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('delegate', 'Delegate'), ('representative', 'Representative'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='delegate', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_access_request', to='councilApp.delegate')),
            ],
            options={
                'db_table': 'AdminAccessRequest',
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('badge', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField(blank=True)),
                ('links', models.TextField(blank=True, help_text='One markdown link or URL per line.')),
                ('order', models.IntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='councilApp.agendaday')),
            ],
            options={
                'db_table': 'AgendaItem',
                'ordering': ['order', 'id'],
            },
        ),
    ]
