from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index),
	path('index.html', views.index),
	path('discussions/', views.discussions),
	path('discussions/<int:discussion_id>/', views.discussionDetail),
	path('discussions/<int:discussion_id>/logs/', views.discussionLogs),
	path('ajax/discussionJoin/', views.ajaxDiscussionJoin),
	path('ajax/discussionExit/', views.ajaxDiscussionExit),
	path('ajax/discussionArchive/', views.ajaxDiscussionArchive),
	path('ajax/discussionReopen/', views.ajaxDiscussionReopen),
	path('ajax/discussionRename/', views.ajaxDiscussionRename),
	path('ajax/discussionTypeChange/', views.ajaxDiscussionTypeChange),
	path('ajax/discussionAddModerator/', views.ajaxDiscussionAddModerator),
	path('ajax/discussionAddSpeaker/', views.ajaxDiscussionAddSpeaker),
	path('ajax/discussionRemoveSpeaker/', views.ajaxDiscussionRemoveSpeaker),
	path('ajax/discussionReorderSpeakers/', views.ajaxDiscussionReorderSpeakers),
	path('ajax/discussionUpdateSpeakerTime/', views.ajaxDiscussionUpdateSpeakerTime),
	path('ajax/discussionTimerAction/', views.ajaxDiscussionTimerAction),
	path('ajax/discussionQuestionAdd/', views.ajaxDiscussionQuestionAdd),
	path('ajax/discussionQuestionEdit/', views.ajaxDiscussionQuestionEdit),
	path('ajax/discussionQuestionDelete/', views.ajaxDiscussionQuestionDelete),
	path('ajax/discussionQuestionReact/', views.ajaxDiscussionQuestionReact),
	path('ajax/speakerAdd', views.ajaxSpeakerAdd),
	path('ajax/speakerRemove', views.ajaxSpeakerRemove),
	path('ajax/reorderSpeakers', views.ajaxSpeakersReorder),
	path('ajax/clearSpeakers', views.ajaxSpeakersClear),
	path('ajax/changeSpeakingMode', views.ajaxChangeSpeakingMode),
	path('delegates/', views.delegates),
	path('proxy/', views.proxy),
	path('ajax/nominateProxy/', views.proxyNominate),
	path('ajax/retractProxy/', views.proxyRetract),
	path('ajax/resignProxy/', views.proxyResign),
	path('poll/', views.poll),
	path('poll/create/', views.createPoll),
	path('poll/close/<int:pollId>/', views.closePoll),
	path('poll/<int:pollId>/', views.pollInfo),
	path('vote/<int:pollId>/', views.voteOnPoll),
	path('ajax/getActiveVotes/', views.ajaxGetCastVotes),
	path('ajax/submitVotes/', views.ajaxSubmitVotes),
	path('agenda/', views.agenda),
	path('login/', views.loginCustom),
	path('logout/', views.logoutCustom),
	path('password_change_request/', views.passwordResetLinkRequest),
	path('password_reset/<str:token>/', views.passwordReset),
	path('password_reset_logged/', views.passwordResetLoggedIn),
	path('profile/', views.profile),
	path('registration/', views.regoRequest),
	path('activate/<str:token>/', views.regoSetPassword),
	path('loaderio-' + settings.LOADERIO_TOKEN + '.txt', views.loaderio_token),
	path('app_admin/', views.appAdmin),
	path('app_admin/download_data/', views.appAdminDownloadData),
	path('app_admin/add_users/', views.appAdminAddUsers),
	path('app_admin/add_users_template/', views.appAdminAddUsersTemplate),
	path('app_admin/valid_institutions/', views.appAdminAddUsersValidInstitutions),
	path('app_admin/valid_institutions/download/', views.appAdminAddUsersValidInstitutionsDownload),
	path('app_admin/assign_reps/', views.appAdminAssignReps),
	path('app_admin/assign_rep/<int:instId>/', views.appAdminAssignRepById),
	path('ajax/assignRep/', views.ajaxAssignRep),
	path('ajax/ResetAndWipe/', views.ajaxResetAndWipe),
	path('ajax/addOneUser/', views.ajaxAddOneUser),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
